### ISSUE TITLE
How to generate boards.html

### ISSUE THREAD

**Issue by metalbug** [ctrlcctrlv/infinity#293]
I don't know "Browse existing boards" is how to generate?

**Comment by milezteg** [comment]
Old thread but still relevant as I run into it on current build.

It seems to be a chicken and egg situation with all of the extra html files you generate with cron.  Because the files are not included in your repo initially, they cannot be generated.  Results in this error for instance with boards.php:

`#php boards.php`
`Uncaught exception 'Exception' with message 'Template file '8chan/boards-index.html' does not exist or is empty in '/var/www/888/templates'!' in /var/www/888/inc/template.php:78`

So it complains the file isn't there and we can't generate one, unless I am missing something...?

**Comment by milezteg** [comment]
Hah solution is obvious after reviewing templates.php...just make sure the files are not empty.  Create them and add a whitespace.  I can see from searching here others have run into this.

**Comment by milezteg** [comment]
Hmm actually it appears this doesn't work and boards-index.html is simply missing.  Could this be added to the repo?
