### ISSUE TITLE
board CSS should be applied on top of styles

### ISSUE THREAD

**Issue by bui** [ctrlcctrlv/infinity#418]
rather than it being its own style, which can only use Yotsuba B as a base, because using something like Tomorrow is impossible unless the whole stylesheet is added to board CSS

there should be a toggle for each board to enable/disable board CSS, while being able to freely switch styles without affecting board CSS

**Comment by 8n-tech** [comment]
This isn't an issue anymore and needs to be closed.

user-css.js
`$('.user-chosen-stylesheet,#stylesheet').remove();`

Board CSS is removed if the user has custom CSS.

**Comment by bui** [comment]
@8n-tech what? that is not relevant to the issue

**Comment by 8n-tech** [comment]
@bui I'm having trouble understanding the issue. There's multiple layers of CSS.

 -  Default Stylesheet (First to apply)
 -  Custom Board CSS
 -  Custom User Stylesheet (Disables Custom Board CSS)
 -  Custom User CSS (Last to apply)

Where is the issue happening? Your ticket makes it sound like you want to disable Custom Board CSS if you've enabled a Custom User Stylesheet.

**Comment by bui** [comment]
@8n-tech sorry, what's "Custom User Stylesheet"? does that mean non-default themes eg. Yotsuba, Tomorrow?

if so, yes, the issue is that the custom board CSS is "disabled". custom board CSS should be applied on top of the theme. there are many people who like to use non-default themes, but by applying them they are missing out on the custom board CSS.

I hope this picture clarifies it:

![image](https://cloud.githubusercontent.com/assets/1788767/7186528/68f85ee8-e4a5-11e4-918d-5711ac673a1f.png)

**Comment by 8n-tech** [comment]
Yeah that's what I figured, which is why I quoted that line of code.

`$('.user-chosen-stylesheet,#stylesheet').remove();`

This intentionally removes the custom board CSS. It's by design.

The issue with having board CSS lay on top of the custom CSS is that you can get some imperfections. People who aren't testing their board in every custom stylesheet may have issues like unreadable text. It would generally degrade the user experience.

That's just my two cents. It's not a difficult thing to change but the implications are extremely visible.

**Comment by ctrlcctrlv** [comment]
agreed with @8n-tech 

feature not a bug
