### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by anonfagola** [ctrlcctrlv/infinity#444]
<b>NO NOT REMOVING ANONYMITY OR ANYTHING LIKE THAT READ IT FAGGOT</b>
I think users should be able to make accounts. In these accounts they would be able to create multiple boards (removing the need for multiple admin accounts) and have User CSS and User JS preferences (So that they automatically do what they want when they go on a different computer. It would still fill in the textarea though, so they could edit it. Then when they want, they could edit in on their account). Accounts should probably NEVER be able to use for posting.

**Comment by ctrlcctrlv** [comment]
I'm skeptical of this. That's what the import/export of localStorage is supposed to be for

It adds needless auth bloat all over the place as well, because every pageload we'd need to check if authenticated and push them their settings. It also would provide a *means* to track users across accounts, even if it's not used to that end.

So no.
