### ISSUE TITLE
Favorite bug in Pale Moon

### ISSUE THREAD

**Issue by Elemarkef** [ctrlcctrlv/infinity#512]
Myself and a few other users of Pale Moon are unable to use the favorites list to favorite boards. 

A long time ago I was able to add a board to my favorites. Now I am unable to remove, add, move or do anything else with the favorite list. I've tried clearing cookies and clearing all my 8chan options, but the board I added ages ago is still there and the list still can't be edited

**Comment by ctrlcctrlv** [comment]
Supporting outdated versions of Firefox (which is all Palemoon is) is not a priority.

Update your browser to the latest FF.

**Comment by Elemarkef** [comment]
I'd rather eat a bucket of rusty nails than use Australis, so no thanks. I'll just learn to cope with broken features.

**Comment by ctrlcctrlv** [comment]
lol

well if it's any consolation you're not the only one complaining about broken feaetures and firefox addons

i'm sure the pale moon devs will update the version of gecko in PM soon as it's getting really outdated and lots of peole are leaving it

**Comment by Elemarkef** [comment]
>a lot of people are leaving it. 
For what? going back to firefox? or is there another alternative I'm not aware of?

I can only hope PM gets an update, using firefox or chrome is not an appealing option

**Comment by ctrlcctrlv** [comment]
I did some research into the issue myself. 

Cyberfox (https://cyberfox.8pecxstudios.com/ : based on FF 38), Waterfox (https://www.waterfoxproject.org/ : based on FF 38), et cetera, all have updated Gecko.

Basically Pale Moon has been around since 2013, and followed upstream Firefox closely until Firefox version 24. After a feature was released that the developer did not like in 24, PM decided to stick with Firefox 24 forever and just add to it and not pull in Gecko changes anymore. The problem with this is that Firefox is a moving target and Mozilla has many more devs than PM does. Unless Moonchild relents and updates PM's Gecko it's just going to get worse and worse, with more popular addons and websites breaking on Pale Moon as they implement APIs that are in the newer versions of Firefox but not in Firefox 24.

**Comment by dfkt** [comment]
Elemarkef, you don't need to eat a bucket of rusty nails: 
https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/
https://addons.mozilla.org/en-US/firefox/addon/status-4-evar/

**Comment by wolfbeast** [comment]
@ctrlcctrlv You should get your facts straight and stop drinking the Firefox fanboi cool-aid so much.
- If you want to talk about pointless rebuilds, your choice is any *fox out there.
- If you want to talk about a FORK, then Pale Moon is indeed what you'd be looking at. As the only real Mozilla fork, at that.
- It's not outdated
- Relevant and desired feature changes from Firefox are adopted.
- There is no reason to wholesale adopt the abomination that Firefox has become
- "After a feature was released that the developer did not like in 25, PM decided to stick with Firefox 24 forever and just add to it and not pull in Gecko changes anymore." Not sure where you get your info but this is absolutely wrong, and sounds like someone "assuming this happened" because the rabid version ticking was stopped.

If you feel there's something essential missing in the browser that you are using, please open an issue on https://github.com/MoonchildProductions/Pale-Moon and we'll look into it. Please also see the roadmap to know our approach to the non-standard web (the risk anyone takes with implementing essential features based on W3C Editors **draft specs** is big.

**Comment by ctrlcctrlv** [comment]
> Please also see the roadmap to know our approach to the non-standard web (the risk anyone takes with implementing essential features based on W3C Editors draft specs is big.

This betrays the rest of your comment.

First of all, we are discussing the main.js program, which is a user script that makes the site a bit easier to use. It's not essential for the site's operation, but it quite often makes use of "draft specs" such as [localStorage](http://www.w3.org/TR/webstorage/) and HTML5. (hardly drafts in anyone's mind but the W3C's, these have been around for years in most browsers)

It is up to you to support the web as it is. If you feel that you can dawdle on "draft specs", that's fine, but then your web browser is out of date and won't work *perfectly* with many sites, seems quite simple to me. Infinity is made for creating imageboards, but you can just as easily post to it via lynx or w3m, terminal browsers which don't even support images, so the raw POST mechanism won't ever disappear. However the more you cling to your lone-wolf (hehe) Mozilla fork and the more Mozilla supersedes it in features, the more they will diverge until Pale Moon will be right next to lynx/w3m with best ways to post on the site. (People do post via w3m/lynx, I see the user agents.)

**Comment by wolfbeast** [comment]
I repeat:
If you feel there's something essential missing in the browser that you are using, please open an issue on https://github.com/MoonchildProductions/Pale-Moon and we'll look into it.

The rest of my comment does need consideration (and doesn't contradict anything in the mention of a risk using non-standardized code, which is all I mentioned it for) since you're obviously misinformed about Pale Moon and should consider supporting a broader base for a public site. **You are also free to use Firefox as a measuring rod, but in that case any other that isn't Mozilla Firefox with the exact feature set it offers will fall short** (including IE, Chrome, Safari, Opera, and what not) because they choose to implement different parts of the draft specs - and hold off on those that are still very much in flux or are considered undesirable. Try to approach it from a more neutral standpoint, if you will. The same way I can call infinity flawed because it's not exactly the same as vichan.

As a framework developer, you need to keep your own approach flexible - if not, then you are cutting short (and basically discriminating against) users' choice of clients. There's already enough of that going on on the "Open Web" by large corporations - please don't join those ranks if you can help it.

What you are discussing is obviously the core of your work here - but it clearly made a dismissive and incorrect statement about Pale Moon as a response to a clear issue with *your* code by making the choice to not cater to "anything but the latest FF" with obviously some issue in coding where it thinks that Pale Moon = FF (which it isn't, unlike others that just rebuild with minimal front-end changes - more about that soon in our own "neck of the woods" (haha)):

> Supporting outdated versions of Firefox (which is all Palemoon is) is not a priority.
Update your browser to the latest FF.

Feel free to go your own way and be inflexible, if you insist, but I'll make clear to our users that it is an error in your scripting assuming certain features without testing for them if they complain - because that is what it boils down to.

**Comment by JamesTheAwesomeDude** [comment]
So what API exactly is it that's not working in Pale Moon? Is it something standardized that Pale Moon should be supporting? (In which case the onus is on @wolfbeast to find and resolve the issue)  
Or is it something which the major browsers support but isn't "supposed" to be used? (In which case, what *is* the API, and is there a standardized solution?)

On another note, I use exclusively Pale Moon and the favorites feature has not broken for me in recent memory. I just double-checked today, and the favorites can be added, removed, and rearranged without problems. At the moment, I'm running Pale Moon 25.5.0 on Linux Mint 17.1.
